[32m2025-02-24 12:12:25 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 565557a0-aa82-4084-8dbe-12ee4cd5f0e9 - 59227 - LOGS_CAPTURED - Started capturing logs in process (pid: 59227).
[32m2025-02-24 12:12:25 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 565557a0-aa82-4084-8dbe-12ee4cd5f0e9 - 59227 - joined_data_missing_dimension_check - STEP_START - Started execution of step "joined_data_missing_dimension_check".
[32m2025-02-24 12:12:25 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 565557a0-aa82-4084-8dbe-12ee4cd5f0e9 - 59227 - joined_data_missing_dimension_check - STEP_FAILURE - Execution of step "joined_data_missing_dimension_check" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "joined_data_missing_dimension_check"::

duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "joined_data" of type "AssetsDefinition" found on line "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/etl_tutorial/definitions.py:131" not suitable for replacement scans.
Make sure that "joined_data" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format

Stack Trace:
  File "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/.venv/lib/python3.13/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
  File "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
        fn, context, kwargs, context_arg_provided, config_arg_class, resource_arg_mapping
    )
  File "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/.venv/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ~~^^^^^^^^^^^^^^^^
  File "/Users/erik/Code/github.com/erikwrightvbt/dagster_tutorial/etl_tutorial/definitions.py", line 131, in missing_dimension_check
    query_result = conn.execute(
                   ~~~~~~~~~~~~^
        """
        ^^^
    ...<3 lines>...
        """
        ^^^
    ).fetchone()
    ^
[0m
